
# .github/workflows/deploy-rsync.yml
name: Deploy Frontend with Rsync to EC2

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}
      VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
      VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Vite App
        working-directory: ./frontend
        run: npm run build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 3.132.167.245 >> ~/.ssh/known_hosts

      - name: Rsync to EC2 NGINX Directory
        run: |
          rsync -az --delete -e "ssh -i ~/.ssh/id_rsa" frontend/dist/ ec2-user@3.132.167.245:/usr/share/nginx/html/
